services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bomnet_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - bomnet

  auth-server:
    build: ./backend/auth
    container_name: auth-server
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - bomnet

  core-server:
    build: ./backend/core
    container_name: core-server
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    networks:
      - bomnet

  notification-server:
    build: ./backend/notification
    container_name: notification-server
    ports:
      - "8084:8084"
    depends_on:
      - mariadb
    networks:
      - bomnet

  frontend:
    build: ./frontend
    container_name: front
    ports:
      - "5173:5173"
    networks:
      - bomnet

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      auth-server:
        condition: service_started
      core-server:
        condition: service_started
    networks:
      - bomnet
  llm-server:
    build: ./backend/llm
    container_name: llm-server
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    networks:
      - bomnet
    volumes:
      - ./backend/llm:/app
  bridge-server:
    build: ./backend/bridge
    container_name: bridge-server
    ports:
      - "8100:8100"
    depends_on:
      - mariadb
    networks:
      - bomnet
    volumes:
      - ./backend/bridge:/app

volumes:
  mariadb_data:

networks:
  bomnet:
    name: bomnet
    driver: bridge

# docker rmi -f $(docker images -q) - 모든이미지 삭제
# docker rm $(docker ps -aq) - 모든 컨테이너 삭제
# docker network prune -f - 기본 네트워크 제외 모든 네트워크 삭제
# docker-compose up -d --build -  빌드 후 실행
# docker-compose down - 실행중지
# docker builder prune -a - 빌드캐시삭제
# docker-compose restart {컨테이너 이름} - 특정 컨테이너 재시작