apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: front
    repoURL: https://github.com/Bombi-goorm/BomArgo
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
