spring:
  application:
    name: auth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: :${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: "https://auth.bomnet.shop/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE}



server:
  port: ${AUTH_PORT}

jwt:
  secret: ${JWT_SECRET}